#\\           //#
# \\         // #
# |\\       //| #
# ||\\     //|| #
# || RAYMBOX || #		MAKEFILE
# ||//     \\|| #		PISCINE CPP FORMAT
# |//       \\| #
# //         \\ #
#//           \\#

#PROGRAM NAME-------------------------------------------------------------------

NAME 			= sed_is_for_loser

#CPP_LIST-----------------------------------------------------------------------
#  find ./*.cpp -type f | cut -c3- | sed 's/$/ \\/'

SRCS			=	main.cpp
					

#HPP_LIST-----------------------------------------------------------------------
#  find ./*.hpp -type f | cut -c3- | sed 's/$/ \\/'

HEADERS			=	

#PROJECT EXPLANATION------------------------------------------------------------
define EXPLANATION
--------------------------------------------------------------------------------
MODULE 01 _ EX04 _ SED, C'EST POUR LES PERDANT(E)S

Concevoir un programme qui creara une copie d'un fichier 
	- en changeant une string par une autre
	- et qui aura le meme nom mais terminant par ".replace" 

Le programme recevra en parametre dans l'ordre
	- filename
	- string a remplacer
	- string qui remplace

Outils
	- make file = Creer deux files pour les tests 
		- chapter1 (extrait du chapitre 1 de The Hitchhiker’s Guide to the Galaxy)
		- simple (File courte et simple servant aussi pour make test)
	- make test = Execute une serie de tests
--------------------------------------------------------------------------------
endef
export EXPLANATION

define ART

███████╗██╗██╗░░░░░███████╗░░░░░░██╗░░███████╗██╗██╗░░░░░███████╗
██╔════╝██║██║░░░░░██╔════╝░░░░░░╚██╗░██╔════╝██║██║░░░░░██╔════╝
█████╗░░██║██║░░░░░█████╗░░█████╗░╚██╗█████╗░░██║██║░░░░░█████╗░░
██╔══╝░░██║██║░░░░░██╔══╝░░╚════╝░██╔╝██╔══╝░░██║██║░░░░░██╔══╝░░
██║░░░░░██║███████╗███████╗░░░░░░██╔╝░██║░░░░░██║███████╗███████╗
╚═╝░░░░░╚═╝╚══════╝╚══════╝░░░░░░╚═╝░░╚═╝░░░░░╚═╝╚══════╝╚══════╝

endef
export ART

FILE		= 	chapter1 \
				chapter1.replace \
				simple \
				simple.replace
#FILE
define FILE1
Chapter One

The house stood on a slight rise just on the edge of the village. It stood on its own and looked out over a broad spread of West Country farmland. Not a remarkable house by any means—it was about thirty years old, squattish, squarish, made of brick, and had four windows set in the front of a size and proportion which more or less exactly failed to please the eye.

The only person for whom the house was in any way special was Arthur Dent, and that was only because it happened to be the one he lived in. He had lived in it for about three years, ever since he had moved out of London because it made him nervous and irritable. He was about thirty as well, tall, dark-haired and never quite at ease with himself. The thing that used to worry him most was the fact that people always used to ask him what he was looking so worried about. He worked in local radio which he always used to tell his friends was a lot more interesting than they probably thought. It was, too—most of his friends worked in advertising.

On Wednesday night it had rained very heavily, the lane was wet and muddy, but the Thursday morning sun was bright and clear as it shone on Arthur Dent’s house for what was to be the last time.

It hadn’t properly registered yet with Arthur that the council wanted to knock it down and build a bypass instead.


At eight o’clock on Thursday morning Arthur didn’t feel very good. He woke up blearily, got up, wandered blearily round his room, opened a window, saw a bulldozer, found his slippers, and stomped off to the bathroom to wash.

Toothpaste on the brush—so. Scrub.

Shaving mirror—pointing at the ceiling. He adjusted it. For a moment it reflected a second bulldozer through the bathroom window. Properly adjusted, it reflected Arthur Dent’s bristles. He shaved them off, washed, dried and stomped off to the kitchen to find something pleasant to put in his mouth.

Kettle, plug, fridge, milk, coffee. Yawn.

The word bulldozer wandered through his mind for a moment in search of something to connect with.

The bulldozer outside the kitchen window was quite a big one.

He stared at it.

'Yellow,' he thought, and stomped off back to his bedroom to get dressed.

Passing the bathroom he stopped to drink a large glass of water, and another. He began to suspect that he was hung over. Why was he hung over? Had he been drinking the night before? He supposed that he must have been. He caught a glint in the shaving mirror. “Yellow,” he thought, and stomped on to the bedroom.

He stood and thought. The pub, he thought. Oh dear, the pub. He vaguely remembered being angry, angry about something that seemed important. He’d been telling people about it, telling people about it at great length, he rather suspected: his clearest visual recollection was of glazed looks on other people’s faces. Something about a new bypass he’d just found out about. It had been in the pipeline for months only no one seemed to have known about it. Ridiculous. He took a swig of water. It would sort itself out, he’ d decided, no one wanted a bypass, the council didn’t have a leg to stand on. It would sort itself out.

God, what a terrible hangover it had earned him though. He looked at himself in the wardrobe mirror. He stuck out his tongue. 'Yellow,' he thought. The word yellow wandered through his mind in search of something to connect with.

Fifteen seconds later he was out of the house and lying in front of a big yellow bulldozer that was advancing up his garden path.


Mr. L. Prosser was, as they say, only human. In other words he was a carbon-based bipedal life form descended from an ape. More specifically he was forty, fat and shabby and worked for the local council. Curiously enough, though he didn’t know it, he was also a direct male-line descendant of Genghis Khan, though intervening generations and racial mixing had so juggled his genes that he had no discernible Mongoloid characteristics, and the only vestiges left in Mr. L. Prosser of his mighty ancestry were a pronounced stoutness about the tum and a predilection for little fur hats.

He was by no means a great warrior; in fact he was a nervous, worried man. Today he was particularly nervous and worried because something had gone seriously wrong with his job, which was to see that Arthur Dent’s house got cleared out of the way before the day was out.

“Come off it, Mr. Dent,” he said, “you can’t win, you know. You can’t lie in front of the bulldozer indefinitely.” He tried to make his eyes blaze fiercely but they just wouldn’t do it.

Arthur lay in the mud and squelched at him.

“I’m game,” he said, “we’ll see who rusts first.”

“I’m afraid you’re going to have to accept it,” said Mr. Prosser, gripping his fur hat and rolling it round the top of his head; “this bypass has got to be built and it’s going to be built!”

“First I’ve heard of it,” said Arthur, “why’s it got to be built?”

Mr. Prosser shook his finger at him for a bit, then stopped and put it away again.

“What do you mean, why’s it got to be built?” he said. “It’s a bypass. You’ve got to build bypasses.”

Bypasses are devices that allow some people to dash from point A to point B very fast while other people dash from point B to point A very fast. People living at point C, being a point directly in between, are often given to wonder what’s so great about point A that so many people from point B are so keen to get there, and what’s so great about point B that so many people from point A are so keen to get there. They often wish that people would just once and for all work out where the hell they wanted to be.

Mr. Prosser wanted to be at point D. Point D wasn’t anywhere in particular, it was just any convenient point a very long way from points A, B and C. He would have a nice little cottage at point D, with axes over the door, and spend a pleasant amount of time at point E, which would be the nearest pub to point D. His wife of course wanted climbing roses, but he wanted axes. He didn’t know why—he just liked axes. He flushed hotly under the derisive grins of the bulldozer drivers.

He shifted his weight from foot to foot, but it was equally uncomfortable on each. Obviously somebody had been appallingly incompetent and he hoped to God it wasn’t him.

Mr. Prosser said, “You were quite entitled to make any suggestions or protests at the appropriate time, you know.”

“Appropriate time?” hooted Arthur. “Appropriate time? The first I knew about it was when a workman arrived at my home yesterday. I asked him if he’d come to clean the windows and he said no, he’d come to demolish the house. He didn’t tell me straight away of course. Oh no. First he wiped a couple of windows and charged me a fiver. Then he told me.”

“But Mr. Dent, the plans have been available in the local planning office for the last nine months.”

“Oh yes, well, as soon as I heard I went straight round to see them, yesterday afternoon. You hadn’t exactly gone out of your way to call attention to them, had you? I mean, like actually telling anybody or anything.”

“But the plans were on display . . .”

“On display? I eventually had to go down to the cellar to find them.”

“That’s the display department.”

“With a flashlight.”

“Ah, well, the lights had probably gone.”

“So had the stairs.”

“But look, you found the notice, didn’t you?”

“Yes,” said Arthur, “yes I did. It was on display in the bottom of a locked filing cabinet stuck in a disused lavatory with a sign on the door saying ‘Beware of the Leopard.’”

A cloud passed overhead. It cast a shadow over Arthur Dent as he lay propped up on his elbow in the cold mud. It cast a shadow over Arthur Dent’s house. Mr. Prosser frowned at it.

“It’s not as if it’ s a particularly nice house,” he said.

“I’m sorry, but I happen to like it.”

“You’ ll like the bypass.”

“Oh, shut up,” said Arthur Dent. “Shut up and go away, and take your bloody bypass with you. You haven’t got a leg to stand on and you know it.”

Mr. Prosser’s mouth opened and closed a couple of times while his mind was for a moment filled with inexplicable but terribly attractive visions of Arthur Dent’ s house being consumed with fire and Arthur himself running screaming from the blazing ruin with at least three hefty spears protruding from his back. Mr. Prosser was often bothered with visions like these and they made him feel very nervous. He stuttered for a moment and then pulled himself together.

“Mr. Dent,” he said.

“Hello? Yes?” said Arthur.

“Some factual information for you. Have you any idea how much damage that bulldozer would suffer if I just let it roll straight over you?”

Copyright © 1997 by Douglas Adams

endef
export FILE1

define FILE2
A 1 CC
B 2 DD
C 1 EE
D 2 FF
E 1 AA
F 2 BB
G 1 CC
endef
export FILE2


#DIRECTORY----------------------------------------------------------------------

OBJS_DIR		= 	./obj

#SYSTEM VAR---------------------------------------------------------------------

CFLAGS 			= 	-Wall -Werror -Wextra -std=c++98
CC				= 	g++
CC_DEBUG		=	g++ -g

RM				= 	rm -rf
LEAK_CMD		=	leaks --atExit --

R = $(shell tput -Txterm setaf 1)
G = $(shell tput -Txterm setaf 2)
W = $(shell tput -Txterm setaf 7)
C = $(shell tput -Txterm setaf 6)
Y = $(shell tput -Txterm setaf 3)
Z = $(shell tput -Txterm setaf 5)

#OBJ----------------------------------------------------------------------------

OBJS 			= 	$(SRCS:%.cpp=$(OBJS_DIR)/%.o)

$(OBJS_DIR)/%.o:%.cpp $(HEADERS)
	@$(CC) $(CFLAGS) -c $< -o $@

#RULES--------------------------------------------------------------------------

all: 	init $(NAME)
		

$(NAME): $(OBJS)
			@$(CC) $(CFLAGS) $(OBJS) -o $(NAME)
			@echo "$G$$ART$W"
			@echo "$G$(NAME) ready!$W"
			
init:
			@mkdir -p $(OBJS_DIR)

clean:
			@$(RM) $(OBJS)
			@$(RM) $(OBJS_DIR)
			@echo "$RObjects removed$W"

fclean: clean
			@$(RM) $(NAME)
			@$(RM) $(FILE)
			@$(RM) $(NAME)_debug
			@$(RM) $(NAME)_debug.dSYM
			@echo "$RExecutable $(NAME) deleted$W"

goal:
			@echo "$C$$EXPLANATION$W"

leak:
			$(LEAK_CMD) ./$(NAME)

art:
			@echo "$G$$ART$W"

file:
			@echo "$$FILE1" > chapter1
			@echo "$$FILE2" > simple

test:
			@make file
			@echo "\n$YTEST 1: number of argument"
			@echo "\n$YTEST 1a: no argument$C"
			$(LEAK_CMD) ./$(NAME)
			@echo "$Wpress enter to continue"
			@read
			@echo "\n$YTEST 1b: one argument$C"
			$(LEAK_CMD) ./$(NAME) simple
			@echo "$Wpress enter to continue"
			@read
			@echo "\n$YTEST 1c: two arguments$C"
			$(LEAK_CMD) ./$(NAME) simple a
			@echo "$Wpress enter to continue"
			@read
			@echo "\n$YTEST 1d: four arguments$C"
			$(LEAK_CMD) ./$(NAME) notexist a b c
			@echo "$Wpress enter to continue"
			@read
			@echo "$YTEST 2: not existing file$C"
			$(LEAK_CMD) ./$(NAME) notexist "A" "ALLO"
			@echo "$Wpress enter to continue"
			@read
			@echo "$YTEST 3: empty arg"
			@echo "$YTEST 3a: empty filename$C"
			$(LEAK_CMD) ./$(NAME) "" "a" "ALLO"
			@echo "$Wpress enter to continue"
			@read
			@echo "$YTEST 3b: empty find string$C"
			$(LEAK_CMD) ./$(NAME) simple "" "ALLO"
			@echo "$Wpress enter to continue"
			@read
			@echo "$YTEST 3c: empty replace string$C"
			$(LEAK_CMD) ./$(NAME) simple "A" ""
			@echo "$Wpress enter to continue"
			@read
			@echo "$YTEST 4: real try$C"
			$(LEAK_CMD) ./$(NAME) simple "A" "ALLO"
			@echo "$Wpress enter to continue"
			@read
			@echo "$YResult of < ./sed_is_for_loser simple "A" "ALLO" >$C"
			cat simple
			@echo "$Z"
			cat simple.replace
			@echo "$W"
			
debug:	fclean
			@$(CC_DEBUG) $(CFLAGS) $(SRCS) -o $(NAME)_debug
			@echo "$YDebbuging executable ready!$W"

re:			fclean all

#PHONY--------------------------------------------------------------------------

.PHONY:				all clean fclean re init goal test art leak